name: tortilla_digital
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  get: ^4.7.2
  intl: ^0.18.1   # <-- Para manejar fechas

  # Firebase y servicios
  firebase_core: ^3.8.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.4
  firebase_storage: ^12.3.4

  # Image Picker
  image_picker: ^1.1.2
  shared_preferences: ^2.2.2
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/tortilla.png
    - assets/usuarios.json
    - assets/avatar.png
